name: qgrid-environment
channels:
  - conda-forge
  - defaults
dependencies:
  - jupyterlab
  - qgrid
  - pandas-datareader>=0.5.0
  - matplotlib>=2.1.1
  - pip
  - pip:
    - ipywidgets
    - qgrid
    - cufflinks
    - plotly==4.3.0
    - numpy
    - nbinteract
